# https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/
sudo: required
services:
  - docker
language: bash
script:
  - cd ./raspberry
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t $DOCKER_USER/docker-magicmirror:raspberry .
  - cd ..
  - docker build -t $DOCKER_USER/docker-magicmirror:latest .
  - cd ./alpine
  - docker build -t $DOCKER_USER/docker-magicmirror:alpine .
after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      docker push $DOCKER_USER/docker-magicmirror:raspberry
      docker push $DOCKER_USER/docker-magicmirror:latest
      docker push $DOCKER_USER/docker-magicmirror:alpine
    fi
