sudo: required
services:
  - docker
language: bash
script:
  - docker build -t $DOCKER_USER/docker-magicmirror:latest .
  - docker build -t $DOCKER_USER/docker-magicmirror:raspberry -f ./raspberry/Dockerfile .
after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      docker push $DOCKER_USER/docker-magicmirror:raspberry
      docker push $DOCKER_USER/docker-magicmirror:latest
    fi
